pushup= Exercise.create(name: "Pushups", category: "Chest", equipment: "None", description: "Lower your body down until your chest almost reaches the floor. Press your body back up to the starting position while squeezing your chest. Pause briefly at the top before repeating.")
bench_press= Exercise.create(name: "Bench Press", category: "Chest", equipment: "Barbell", description: "Hold a barbell with your hands shoulder-width apart and lower the bar until it skims the middle of your chest. Push the barbell back to the starting position explosively as you breathe out.")
incline_bench= Exercise.create(name: "Incline Bench Press", category: "Chest", equipment: "Barbell", description: "Hold a barbell with your hands shoulder-width apart and lower the bar until it skims the upper-middle part of your chest. Push the barbell back to the starting position explosively as you breathe out.")
dumbbell_press= Exercise.create(name: "Dumbbell Bench Press", category: "Chest", equipment: "Dumbbells", description: "Lift the dumbbells over your chest, palms facing away from you. Slowly lower the weights to the outside of your chest and drive them back up while squeezing your chest.")
cable_fly= Exercise.create(name: "Cable Fly", category: "Chest", equipment: "Cables", description: "Place one foot slightly forward, brace your core, and pull the handles downward and across your body. Return to the start position slowly and under control.")
dumbbell_fly= Exercise.create(name: "Dumbbell Fly", category: "Chest", equipment: "Dumbbells", description: "Take two dumbbells and lay on a bench, make sure the feet are firmly on the ground and your back is not arched, but has good contact with the bench. The arms are stretched in front of you, about shoulder wide. Bend the arms a bit and let them down with a half-circle movement to the side. Without changing the angle of the elbow bring them in a fluid movement back up.")
chest_press= Exercise.create(name: "Machine Chest Press", category: "Chest", equipment: "Machine Chest Press", description: "Hold the handles shoulder width apart. Explosively push, extending your arms. Slowly lower the weight back down to the starting position and repeat.")
chest_dips= Exercise.create(name: "Chest Dips", category: "Chest", equipment: "Dip/Pullup Station", description: "Grab the bars of a dip station with your palms facing inward and your arms straight. Slowly lower until your elbows are at right angles, ensuring they stay tucked against your body and don't flare out. Drive yourself back up to the top and repeat.")

curls= Exercise.create(name: "Dumbbell Curl", category: "Arms", equipment: "Dumbbells", description: "Hold two barbells with your arms extended and hands at your side.Bend the arms and bring the weight with a fast movement up. At the same time, rotate your arms by 90 degrees at the very beginning of the movement. At the highest point, rotate the weights outwards. Without a pause, bring them down, slowly.")
preacher_curl= Exercise.create(name: "Preacher Curl", category: "Arms", equipment: "Preacher Machine", description: "Hold the handles with a neutral grip and curl towards you. Squeeze at the top and slowly lower the weight back to the starting position.")
hammer_curl= Exercise.create(name: "Hammer Curl", category: "Arms", equipment: "Dumbbells", description: "Hold the dumbbells at arm's length with your palms facing your thighs. Bend your elbows and curl the dumbbells as close to your shoulders as possible. Pause at the top and slowly lower the weight back to the starting position.")
waiter_curl= Exercise.create(name: "Waiter Curl", category: "Arms", equipment: "Dumbbells", description: "Hold a single dumbbell in front of your body with your palms facing upward. Bracing your elbows against your body, curl the weight directly upwards and squeeze at the top. Slowly bring the weight back to the starting position.")
ez_curl = Exercise.create(name: "E-Z Bar Curl", category: "Arms", equipment: "E-Z Bar", description: "Hold the bar on the inside grips or the outside grips. Slowly curl the weight up without swinging your back. Lower the weight back down with control.")
decline_curl = Exercise.create(name: "Decline Dumbbell Curl", category: "Arms", equipment: "Dumbbells", description: "Lie chest down against a bench that’s set to a 45-degree incline. Bend your elbows – don’t move your upper arms and curl the dumbbells up to your shoulders.")
chin_up = Exercise.create(name: "Chin-up", category: "Arms", equipment: "Pull-up bar", description: "Grab the bar with your palms facing towards you and a grip that is narrower than shoulder width. Pull yourself up until your head is above the bar. Slowly lower back to the start position.")

skullcrusher= Exercise.create(name: "Skullcrusher", category: "Arms", equipment: "EZ Bar", description: "")
close_grip= Exercise.create(name: "Close-Grip Bench Press", category: "Arms", equipment: "Barbell", description: "")
dips= Exercise.create(name: "Dips", category: "Arms", equipment: "Dip/Pullup Station", description: "")
dumbbell_extension= Exercise.create(name: "Overhead Dumbbell Extension", category: "Arms", equipment: "Dumbbells", description: "")
cable_push = Exercise.create(name: "Cable Push Down", category: "Arms", equipment: "Cables", description: "")
diamond_pushups = Exercise.create(name: "Diamond Pushups", category: "Arms", equipment: "None", description: "")

barbell_press= Exercise.create(name: "Barbell Press", category: "Shoulders", equipment: "Barbell", description: "")
military_press= Exercise.create(name: "Military Press", category: "Shoulders", equipment: "Dumbbells", description: "")
raises= Exercise.create(name: "Lateral Raise", category: "Shoulders", equipment: "Dumbbells", description: "")
arnold_press= Exercise.create(name: "Arnold Press", category: "Shoulders", equipment: "Dumbbells", description: "")
cable_reverse = Exercise.create(name: "Cable Reverse Fly", category: "Shoulders", equipment: "Cables", description: "")
shoulder_press = Exercise.create(name: "Inverted Shoulder Press", category: "Shoulders", equipment: "None", description: "")
front_raises= Exercise.create(name: "Front Raise", category: "Shoulders", equipment: "Dumbbells", description: "")

deadlift= Exercise.create(name: "Deadlift", category: "Back", equipment: "Barbell", description: "")
single_row= Exercise.create(name: "Single-Arm Row", category: "Back", equipment: "Dumbbells", description: "")
row= Exercise.create(name: "Barbell Row", category: "Back", equipment: "Barbell", description: "")
lat_pulldown= Exercise.create(name: "Lat Pull-Down", category: "Back", equipment: "Lat Machine", description: "")
pullup= Exercise.create(name: "Pull-up", category: "Back", equipment: "Pull-up bar", description: "")
dumbbell_row = Exercise.create(name: "Chest Supported Dumbbell Row", category: "Back", equipment: "Dumbbells", description: "")
inverted_row= Exercise.create(name: "Inverted Row", category: "Back", equipment: "Barbell", description: "")
shrugs= Exercise.create(name: "Dumbbell Shrugs", category: "Back", equipment: "Dumbbells", description: "")

legpress= Exercise.create(name: "Leg Press", category: "Legs", equipment: "Press Machine", description: "Make sure your lower back stays pressed against the bench pad at all times throughout the exercise, and you keep your chest high. Release the safety and bend your knees to lower the platform until you feel your glutes wanting to lift off the bench. In a steady motion, push the platform back up to the top without locking your knees.")
squats= Exercise.create(name: "Barbell Squats", category: "Legs", equipment: "Barbell", description: "Holding the barbell across your upper back, stand with your feet shoulder width apart. Begin to lower your body down as if you were sitting in a chair until your thighs are parallel with the floor. Drive the weight up to push yourself back up to the starting position.")
jump_squat= Exercise.create(name: "Jump Squat", category: "Legs", equipment: "None", description: "Stand with your feet shoulder width apart and lower into a squat position until your thighs are parallel to the floor. In an explosive motion, jump up as high as you can, landing with soft knees to avoid injury.")
hack_squat= Exercise.create(name: "Hack Squat", category: "Legs", equipment: "Hack Squat Machine", description: "Place your shoulders and back against the pads with your feet planted flat and firm on the plate. Engage your core, release the safety, and begin to lower yourself down until your thighs are parallel to the platform. Hold for a second, and then drive your heels into the platform to propel yourself back up to the starting position.")
extensions= Exercise.create(name: "Leg Extensions", category: "Legs", equipment: "Leg Extension Machine", description: "Hold onto the side bars for leverage and make sure the rest of your body is stationary so you only engage the quads to lift the weight. Exhale as you pull the weights up and pause for a second before you inhale and bring the weights back down.")
leg_curls = Exercise.create(name: "Lying Leg Curls", category: "Legs", equipment: "Leg Curl Machine", description: " Position your legs so the knees are right below the edge of the bench. Exhale as you curl the lower legs until the hamstrings are fully flexed. Pause at the top and then inhale as you bring your legs back down to the starting position for a full extension.")
lunges= Exercise.create(name: "Lunges", category: "Legs", equipment: "None", description: "Make sure that throughout the lunge, your knee on the front leg never goes past your toes. Engage your core to keep your body steady. Step forward with one foot while bending at the knee and lowering your torso towards the floor. Stop just short of your back knee touching the floor. Push your front foot into the floor as you rise up, bringing your back leg forward to the standing position.")
reverse_lunges= Exercise.create(name: "Reverse Lunges", category: "Legs", equipment: "None", description: "Tighten your core to maintain stability throughout the exercise. Step back with one foot and begin to lower your body until your front thigh is parallel to the floor and your back knee is almost touching the floor. Rise up and step back to the starting position.")
calf_raises= Exercise.create(name: "Calf Raises", category: "Legs", equipment: "None", description: "Stand on the machine or box with the balls of your feet at the edge of the platform and the heels of your feet are hanging off. Breathe out as you rise up, using your calves to push up the weight on the machine or the dumbbells in your hands.")

plank= Exercise.create(name: "Plank", category: "Abs", equipment: "None", description: "Lying face down on the ground, prop yourself up into a forearm plank position. Make sure your elbows are aligned underneath your shoulders, and that your hands are balled up in fists. Your forearms should be parallel to one another.")
side_bend= Exercise.create(name: "Dumbbell Side Bend", category: "Abs", equipment: "Dumbbells", description: "Stand with your feet hip-width apart and hold a dumbbell in your right hand, palm facing inwards towards the torso. Keep your back straight, activate your core, and then bend to the side as far as possible—but only at the waist. Hold for one second at the bottom of your range of motion, and return to start for one rep.")
side_plank= Exercise.create(name: "Side Plank", category: "Abs", equipment: "None", description: "Lie on either side with your forearm flat on the floor, elbow under shoulder, and both legs extended. Body should form a straight line from head to feet, which are either stacked or staggered. Engage your core and lift hips up.")
reverse_crunch= Exercise.create(name: "Reverse Crunch", category: "Abs", equipment: "None", description: "Start lying on back, legs lifted so thighs are perpendicular to ground and knees are bent. Pressing lower back into mat, curl knees into chest to lift hips off the ground. Return to start with control.")
heel_taps= Exercise.create(name: "Heel Taps", category: "Abs", equipment: "None", description: "Start on back with knees bent and feet on ground, hands by hips. Lift chest toward the ceiling, keeping neck relaxed and bringing shoulder blades off the ground. Tap right hand to outside of right ankle, flexing right obliques in the process. Come back to center, keeping shoulders off ground, then tap left hand to outside of left ankle.")
ab_roller= Exercise.create(name: "Ab Roller", category: "Abs", equipment: "Ab Roller", description: "Slowly extend the ab roller away from you while keeping a straight back and the core engaged. Go until you are parallel with the floor and slowly return to the start position.")
machine_crunch= Exercise.create(name: "Machine Crunch", category: "Abs", equipment: "Ab Crunch Machine", description: "Grab the handles and slowly bring your arms to your knees with your abs engaged. Hold briefly and slowly return the start position.")
v_up= Exercise.create(name: "V-Up", category: "Abs", equipment: "None", description: "Start lying on back with legs extended and arms by sides, both on mat. In one movement, lift upper body, arms, and legs, coming to balance on tailbone, forming a 'V' shape with body. Lower body back down.")

stairmaster= Exercise.create(name: "Stair Master", category: "Cardio", equipment: "StairMaster", description: "Climb stairs with your core engaged and without leaning on the handles.")
jogging= Exercise.create(name: "Jogging", category: "Cardio", equipment: "Treadmill", description: "Jog and try to drown the pain with music or thoughts.")
burpees= Exercise.create(name: "Burpees", category: "Cardio", equipment: "None", description: "Stand with your feet shoulder-width apart, weight in your heels, and your arms at your sides. Push your hips back, bend your knees, and lower your body into a squat. Place your hands on the floor directly in front of, and just inside, your feet. Shift your weight onto your hands. Jump your feet back to softly land on the balls of your feet in a plank position. Jump your feet back so that they land just outside of your hands. Reach your arms over head and explosively jump up into the air.")
inclined_walking= Exercise.create(name: "Inclined Walking", category: "Cardio", equipment: "Treadmill", description: "Set treadmill to a moderate incline and speed that is a fast walk.")
bike= Exercise.create(name: "Stationary Bike", category: "Cardio", equipment: "Stationary Bike", description: "Set the resistance to your liking and pedal until you can't anymore.")
sprints= Exercise.create(name: "Sprinting", category: "Cardio", equipment: "None", description: "Sprint 40-50 yards at full speed and rest for a minute.")

#PLANS
plan1= Plan.create(name: "Strong Glutes and Thighs", difficulty: "Moderate", commitment: "2-3 times per week", image: "strong_glutes.jpg", description: "This plan is for anyone who wants to build or tone their hips, thighs and glutes.")
PlanExercise.create(plan: plan1, exercise: squats, sets: "4 sets of 8-12 reps")
PlanExercise.create(plan: plan1, exercise: legpress, sets: "4 sets of 8-12 reps")
PlanExercise.create(plan: plan1, exercise: jump_squat, sets: "3 sets of 12-15 reps")
PlanExercise.create(plan: plan1, exercise: leg_curls, sets: "4 sets of 8-12 reps")
PlanExercise.create(plan: plan1, exercise: lunges, sets: "3 sets of 8-12 reps")

plan2= Plan.create(name: "No Weights Legs", difficulty: "Beginner", commitment: "2-3 times per week", image: "No_weights_legs.jpg", description: "This plan is for anyone who wants to tone their quads, thighs and glutes.")
PlanExercise.create(plan: plan2, exercise: jump_squat, sets: "5 sets of 15-20 reps")
PlanExercise.create(plan: plan2, exercise: lunges, sets: "4 sets of 12-15 reps")
PlanExercise.create(plan: plan2, exercise: reverse_lunges, sets: "4 sets of 12-15 reps")
PlanExercise.create(plan: plan2, exercise: calf_raises, sets: "4 sets of 12-15 reps")
PlanExercise.create(plan: plan2, exercise: burpees, sets: "4 sets of 12-15 reps")

plan3= Plan.create(name: "Power Legs", difficulty: "Advanced", commitment: "1-2 times per week", image: "power_legs.jpg", description: "This plan is for those who want to add size on their quads, hamstrings and glutes.")
PlanExercise.create(plan: plan3, exercise: squats, sets: "5 sets of 4-6 reps")
PlanExercise.create(plan: plan3, exercise: legpress, sets: "4 sets of 6-8 reps")
PlanExercise.create(plan: plan3, exercise: hack_squat, sets: "4 sets of 6-8 reps")
PlanExercise.create(plan: plan3, exercise: extensions, sets: "4 sets of 10-12 reps")
PlanExercise.create(plan: plan3, exercise: leg_curls, sets: "4 sets of 10-12 reps")

plan4= Plan.create(name: "Toned Core", difficulty: "Beginner", commitment: "3-4 times per week", image: "toned_core.jpg", description: "This plan is for those who want to tone their mid-section and bring out ab definition.")
PlanExercise.create(plan: plan4, exercise: v_up, sets: "3 sets of 12-15 reps")
PlanExercise.create(plan: plan4, exercise: reverse_crunch, sets: "3 sets of 15-20 reps")
PlanExercise.create(plan: plan4, exercise: heel_taps, sets: "3 sets of 20-25 reps on each side")
PlanExercise.create(plan: plan4, exercise: side_plank, sets: "3 sets of 30 second holds on each side")
PlanExercise.create(plan: plan4, exercise: plank, sets: "3 sets of 1 minute holds")
PlanExercise.create(plan: plan4, exercise: jogging, sets: "20-45 minutes")

plan4= Plan.create(name: "Shredded Core", difficulty: "Moderate", commitment: "2-3 times per week", image: "shredded.jpg", description: "This plan is for those who want to build ab muscle and condition their abs.")
PlanExercise.create(plan: plan4, exercise: ab_roller, sets: "3 sets of 12-15 reps")
PlanExercise.create(plan: plan4, exercise: reverse_crunch, sets: "3 sets of 15-20 reps")
PlanExercise.create(plan: plan4, exercise: machine_crunch, sets: "3 sets of 15-20 reps")
PlanExercise.create(plan: plan4, exercise: side_bend, sets: "3 sets of 12-15 reps on each side")
PlanExercise.create(plan: plan4, exercise: plank, sets: "3 sets of 1 minute holds")
PlanExercise.create(plan: plan4, exercise: sprints, sets: "6-8 spints at 100%")

plan5= Plan.create(name: "Greek God Chest", difficulty: "Advanced", commitment: "1-2 times per week", image: "greed_chest.jpg", description: "This plan is for those who want to add muscle to their upper and middle chest. ")
PlanExercise.create(plan: plan5, exercise: bench_press, sets: "5 sets of 5-6 reps")
PlanExercise.create(plan: plan5, exercise: incline_bench, sets: "4 sets of 6-8 reps")
PlanExercise.create(plan: plan5, exercise: dumbbell_press, sets: "4 sets of 6-8 reps")
PlanExercise.create(plan: plan5, exercise: chest_press, sets: "4 sets of 10-12 reps")
PlanExercise.create(plan: plan5, exercise: cable_fly, sets: "4 sets of 10-12 reps")

plan6= Plan.create(name: "Toned Chest", difficulty: "Advanced", commitment: "1-2 times per week", image: "toned_chest.jpeg", description: "This plan is for those who want to get a defined chest and build chest strength.")
PlanExercise.create(plan: plan6, exercise: bench_press, sets: "4 sets of 10-12 reps")
PlanExercise.create(plan: plan6, exercise: dumbbell_press, sets: "4 sets of 10-12 reps")
PlanExercise.create(plan: plan6, exercise: dumbbell_fly, sets: "4 sets of 10-12 reps")
PlanExercise.create(plan: plan6, exercise: cable_fly, sets: "4 sets of 10-12 reps")
PlanExercise.create(plan: plan6, exercise: pushup, sets: "3 sets to failure")

plan7= Plan.create(name: "Push-Up Overload", difficulty: "Beginner", commitment: "2-3 times per week", image: "pushups.jpg", description: "This plan is for anyone that needs a chest workout without weights. This plan will help build strength and define the chest muscles.")
PlanExercise.create(plan: plan7, exercise: pushup, sets: "500 pushups throughout the day. However many sets it takes.")



